### PR TITLE
Add simple react-native example

### PR DESCRIPTION
**Pull request by bartonhammond**
Thanks - I like this a whole bunch better then Redux - **way** less boilerplate to write. 

I am in the process of extending my [Snowflake](https://github.com/bartonhammond/snowflake) (932 Stargazers) example for a personal project and was dreading all the Redux cruft.  

I've been looking for days for a more sane approach to writing React-Native and managing the state and I think this project, Mobservable, is the perfect fit for me.  Thanks for making this available.  

I'm thinking of rewriting Snowflake and replacing Redux w/ Mobservable.  It would be an interesting comparison, I think.

### CODE REVIEW

**Comment by mweststrate** [comment]
Thanks! That comparison would definitely be interesting :) Don't hesitate to file issues if you run into any questions.

**Comment by Kosta-Github** [comment]
Yeah, I did the same: started on `react` and `redux` since that seemed to be the current way of doing things, but quickly realized that I don't like the `redux` way of doing things at all.

Right now, I love the way to store all my app-state in a single `mobservable` root object and get a consistent and up-to-date UI out-of-the-box with way less boilerplate code using (more or less) only pure `react` render functions!

:+1:

**Comment by bartonhammond** [comment]
@Kosta-Github Is your code available for me to look at?  I'd like to see some "best practices" before I start writing more.  

Also, have you, or anybody, used any unit testing?  W/ my Redux project I used Jest but I can't get it to work w/ this simple mobservable project.

Thanks...

**Comment by Kosta-Github** [comment]
@bartonhammond: I am sorry, but I cannot share my code...

I am using `mocha` with great success for unit testing.

**Pull request merged**
